version: '3.8'

services:
  keycloak:
    image: jboss/keycloak:11.0.3
    entrypoint: ["/opt/jboss/tools/docker-entrypoint.sh", "-b", "0.0.0.0", "-Dkeycloak.import=/opt/jboss/keycloak/standalone/data/backup_restore/demo-realm.json", "-Dkeycloak.migration.strategy=IGNORE_EXISTING"]
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=*:8787,server=y,suspend=n -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Dkeycloak.profile.feature.impersonation=disabled
    ports:
      - 8888:8080
      - 8787:8787
    volumes:
       - ./docker/backup_restore/:/opt/jboss/keycloak/standalone/data/backup_restore/
       - ./docker/customizations/:/opt/jboss/keycloak/standalone/deployments/
    restart: always
